version: '3.7'

services:

  rtsp-relay:
    build: .
    image: flaviostutz/rtsp-relay
    ports: 
      - 8554:8554
      - 8000:8000
      - 8001:8001
    environment:
      # - SOURCE_URL=http://93.87.72.254:8090/mjpg/video.mjpg
      # - SOURCE_URL=http://wmccpinetop.axiscam.net/mjpg/video.mjpg
      - SOURCE_URL=rtsp://freja.hiof.no:1935/rtplive/definst/hessdalen03.stream
      - RTSP_PROXY_SOURCE_TCP=yes
      # - FORCE_FFMPEG_SOURCE=true
      # - SOURCE_URL=http://ip-thomasmarina.greatlakescam.com/user/cgi-bin/getstream.cgi?10&&&&0&0&0&0&0


      
